## GroupID: AdAnSo

Members:
1. Adarsh Anand (2003101)
2. Aniket Chaudhri (2003104)
3. Somesh Agrawal (20033)


In [3]:
# read A and B matrices from matrix1.txt and matrix2.txt
# and write the result of A*B to matrix3.txt

import numpy as np

# read A and B matrices from matrix1.txt and matrix2.txt
A = np.loadtxt('matrix1.txt')
B = np.loadtxt('matrix2.txt')

In [4]:
# python function to multiply matrices

def matrixmul(A, B):
    C = [[0 for i in range(len(B[0]))] for j in range(len(A))]
    for i in range(len(A)):
        for j in range(len(B[0])):
            for k in range(len(B)):
                C[i][j] += A[i][k] * B[k][j]
    return C


In [2]:
import numpy as np

# numpy multiplication of 2 matrices

def numpymatrixmul(A, B):
    C = np.dot(A, B)
    return C


In [ ]:
print(matrixmul(A, B))

In [6]:
print(numpymatrixmul(A, B))

[[12286. 12105. 11232. ... 12579. 12516. 12567.]
 [13021. 12394. 12357. ... 12992. 12658. 13119.]
 [12122. 11965. 11626. ... 12145. 11974. 12258.]
 ...
 [12142. 12053. 11584. ... 12120. 11642. 12666.]
 [12559. 12105. 11900. ... 12551. 12105. 12946.]
 [12708. 12587. 12043. ... 12721. 12755. 12760.]]
