In [1]:
# neural network functions for implementing forward and backward propagation for a one hidden layer neural network

import numpy as np
import matplotlib.pyplot as plt
import math
import random
import time
import sklearn



In [2]:
# forward multiplication of weights and input W.T * X
def forwardMultiplication(W, X):
    return np.dot(X, W)

# add bias b
def add_bias(X, b):
    return X+b

# sigmoid function
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

# derivative of sigmoid function
def sigmoid_prime(z):
    return sigmoid(z) * (1 - sigmoid(z))

# minimum squared error
def min_squared_error(y, y_hat):
    return np.sum((y-y_hat)**2)

# derivative of minimum squared error
def min_squared_error_prime(y, y_hat):
    return 2*(y_hat-y)

# cross entropy error
def cross_entropy_error(y, y_hat):
    return -np.sum(y*np.log(y_hat))

# derivative of cross entropy error
def cross_entropy_error_prime(y, y_hat):
    return y_hat-y

# softmax function
def softmax(z):
    return np.exp(z) / np.sum(np.exp(z), axis=0)

# derivative of softmax function
def softmax_prime(z):
    return softmax(z) * (1 - softmax(z))

# forward propagation
 




In [45]:
# initialise weights and biases
def init_weights_biases(dim):
    W = np.random.randn(dim, 1) * 0.01
    b = 0
    return W, b

# initialise weights and biases for classifier
def classifier_init_weights_biases(X, Y):
    dim = X.shape[1]
    output_dim = Y.shape[1]
    W = np.random.randn(dim, output_dim) * 0.01
    b = np.zeros((1, output_dim))
    return W, b

def forward_propagation(w, b, X, Y):
    # print("W received", w)
    m = X.shape[0]
    N = forwardMultiplication(w, X)
    P = add_bias(N, b)
    # A = sigmoid(Z)
    loss = min_squared_error(Y, P)
    # loss = cross_entropy_error(Y, P)
    # print("Loss", loss)
    # cost = -1/m * np.sum(Y*np.log(A) + (1-Y)*np.log(1-A))
    return P, loss

def classifier_forward_propagation(w, b, X, Y):
    # print("W received", w)
    m = X.shape[0]
    N = forwardMultiplication(w, X)
    P = add_bias(N, b)
    Q = softmax(P)
    loss = cross_entropy_error(Y, Q)

    return Q, loss

# backward propagation
def backward_propagation(w, b, X, Y, P):
    m = X.shape[0]
    # dZ = A - Y
    dP = min_squared_error_prime(Y, P)
    # dP = cross_entropy_error_prime(Y, P)
    # dw = 1/m * np.dot(X, dP.T)
    dw = np.dot(X.T, dP)
    db = np.sum(dP)
    # db = 1/m * np.sum(dP)
    return dw, db

def classifier_backward_propagation(w, b, X, Y, P):
    m = X.shape[0]
    dQ = cross_entropy_error_prime(Y, P)
    # dP = dQ * softmax_prime(P)
    dP = softmax_prime(dQ)
    dw = np.dot(X.T, dP)
    db = np.sum(dP)
    # db = 1/m * np.sum(dP)
    return dw, db

# update weights and biases
def update_weights_biases(w, b, dw, db, learning_rate):
    w = w - learning_rate * dw
    b = b - learning_rate * db
    return w, b

# predict function
def predict(w, b, X):
    m = X.shape[1]
    N = forwardMultiplication(w, X)
    P = add_bias(N, b)
    # A = sigmoid(Z)
    return P

def classifier_predict(w, b, X):
    m = X.shape[1]
    N = forwardMultiplication(w, X)
    P = add_bias(N, b)
    P_softmax = softmax(P)
    # one hot encode the predictions
    P_softmax = np.eye(10)[P_softmax.argmax(1)]
    
    return P_softmax

# plot loss
def plot_loss(losses):
    plt.plot(losses)
    plt.ylabel('loss')
    plt.xlabel('iterations (per hundreds)')
    plt.title('Loss vs iterations')
    plt.show()

def model(X_train, Y_train, X_test, Y_test, num_iterations, learning_rate, print_cost):
    w, b = init_weights_biases(X_train.shape[0])
    losses = []
    loss = 0
    for i in range(num_iterations):
        P, loss = forward_propagation(w, b, X_train, Y_train)
        dw, db = backward_propagation(w, b, X_train, Y_train, P)
        w, b = update_weights_biases(w, b, dw, db, learning_rate)
        if i % 100 == 0:
            losses.append(loss)
            if print_cost:
                print('Cost after iteration %i: %f' %(i, loss))
    if print_cost:
        print('Cost after iteration %i: %f' %(num_iterations, loss))
    plot_loss(losses)
    return w, b







In [4]:
# def main():
#     # sklearn boston dataset
import pandas as pd
data_url = "http://lib.stat.cmu.edu/datasets/boston"


raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
target = raw_df.values[1::2, 2]
# clean up data
# data = data[:, ~np.isnan(data).any(axis=0)]
# target = target[~np.isnan(data).any(axis=0)]
# normalise data
# data = (data - data.mean(axis=0)) / data.std(axis=0)


print(data)
# print(target)
print(data.shape)
# print(target)

# print(raw_df.head)
   
    



[[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]]
(506, 13)


In [ ]:
# run stochastic gradient descent on the dataset
def run_sgd(X, Y, X_test, Y_test, num_iterations, learning_rate, print_cost, batch_size=1):
    
    # get batch_size training examples and run iterations over them
    # losses = []
    # loss = 0
    # w, b = init_weights_biases(X.shape[1])
    # for batch in range(0, X.shape[0], batch_size):
    #     X_batch = X[batch:batch+batch_size]
    #     Y_batch = Y[batch:batch+batch_size]
        
    #     for i in range(num_iterations):
    #         P, loss = forward_propagation(w, b, X_batch, Y_batch)
    #         dw, db = backward_propagation(w, b, X_batch, Y_batch, P)
    #         w, b = update_weights_biases(w, b, dw, db, learning_rate)
    #         # if i % 100 == 0:
    #         losses.append(loss)
    #         if print_cost:
    #             print('Cost after iteration %i: %f' %(i, loss))
    losses = []
    loss = 0
    w, b = init_weights_biases(X.shape[1])
    for i in range(num_iterations):
        curr_iter_loss = []
        for batch in range(0, X.shape[0], batch_size):
            X_batch = X[batch:batch+batch_size]
            Y_batch = Y[batch:batch+batch_size]
            
            
            P, loss = forward_propagation(w, b, X_batch, Y_batch)
            dw, db = backward_propagation(w, b, X_batch, Y_batch, P)
            w, b = update_weights_biases(w, b, dw, db, learning_rate)
            # if i % 100 == 0:
            losses.append(loss)
            curr_iter_loss.append(loss)
            # if print_cost:
            #     print('Cost after iteration %i: %f' %(i, loss))
        if i%1000:
            print(np.average(curr_iter_loss))


In [ ]:
run_sgd(data, target, data, target, 10, 1e-9, True, 5)

Cost after iteration 0: 3855971.081286
Cost after iteration 100: 683879.226430


In [30]:
run_sgd(data, target, data, target, 10000, 1e-7, True, 2)


Streaming output truncated to the last 5000 lines.
188.21769853702514
188.21115197766167
188.20460927743298
188.19807043150297
188.19153543504422
188.18500428323804
188.17847697127448
188.17195349435218
188.1654338476784
188.15891802646917
188.15240602594895
188.14589784135075
188.13939346791628
188.13289290089565
188.12639613554748
188.11990316713894
188.1134139909455
188.1069286022512
188.10044699634838
188.0939691685378
188.0874951141286
188.0810248284382
188.07455830679234
188.0680955445251
188.0616365369787
188.05518127950378
188.04872976745898
188.04228199621133
188.03583796113597
188.02939765761613
188.02296108104318
188.01652822681666
188.0100990903442
188.00367366704137
187.99725195233188
187.9908339416475
187.9844196304279
187.97800901412072
187.97160208818158
187.96519884807412
187.95879928926976
187.95240340724786
187.94601119749564
187.93962265550815
187.9332377767883
187.92685655684687
187.92047899120226
187.91410507538075
187.90773480491632
187.90136817535065
187.8950051

KeyboardInterrupt: ignored

In [ ]:
run_sgd(data, target, data, target, 10, 1e-9, True, 5)


In [48]:
# load iris dataset from sklearn
from sklearn.datasets import load_iris
iris = load_iris()
X = iris.data
Y = iris.target
# one-hot encode Y
Y = np.eye(3)[Y]


In [49]:
Y

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [46]:
# create a multi-class classifier (Cross entropy loss + soft max)
def multi_class_classifier(X, Y, X_test, Y_test, num_iterations, learning_rate, print_cost, batch_size=1):
    # initialise weights and biases
    w, b = init_weights_biases(X.shape[1])
    # run stochastic gradient descent
    losses = []
    loss = 0
    for i in range(num_iterations):
        curr_iter_loss = []
        for batch in range(0, X.shape[0], batch_size):
            X_batch = X[batch:batch+batch_size]
            Y_batch = Y[batch:batch+batch_size]
            # forward propagation
            P, loss = classifier_forward_propagation(w, b, X_batch, Y_batch)
            # backward propagation
            dw, db = classifier_backward_propagation(w, b, X_batch, Y_batch, P)
            # update weights and biases
            w, b = update_weights_biases(w, b, dw, db, learning_rate)
            # if i % 100 == 0:
            losses.append(loss)
            curr_iter_loss.append(loss)
            # if print_cost:
            #     print('Cost after iteration %i: %f' %(i, loss))
        if i%10:
            print(np.average(curr_iter_loss))

    # print actual and prdeicted value
    print('Actual value: ', Y_test)
    print('Predicted value: ', classifier_predict(w, b, X_test))
    
    # return weights and biases
    return w, b


In [47]:
multi_class_classifier(X, Y, X, Y, 100, 1e-7, True, 2)


2.772642952753092
2.772643003107376
2.7726430542287064
2.772643106117083
2.7726431587725044
2.7726432121949722
2.772643266384484
2.7726433213410404
2.7726433770646417
2.772643490812972
2.772643548837701
2.7726436076294725
2.7726436671882855
2.7726437275141396
2.7726437886070334
2.7726438504669684
2.772643913093942
2.7726439764879554
2.7726441055770965
2.772644171272223
2.7726442377343874
2.772644304963588
2.7726443729598236
2.7726444417230947
2.7726445112534
2.7726445815507406
2.7726446526151136
2.772644797044959
2.77264487041043
2.7726449445429315
2.7726450194424634
2.772645095109026
2.772645171542617
2.772645248743238
2.772645326710885
2.7726454054455605
2.7726455652159907
2.772645646251745
2.7726457280545236
2.7726458106243257
2.772645893961152
2.772645978065001
2.7726460629358716
2.772646148573763
2.7726462349786765
2.7726464100895614
2.7726464987955306
2.772646588268519
2.772646678508525
2.772646769515546
2.772646861289583
2.772646953830635
2.7726470471387
2.7726471412137794
2.772

(array([[-0.02682846, -0.02682846],
        [ 0.01252097,  0.01252097],
        [ 0.02036026,  0.02036026],
        [-0.00565787, -0.00565787]]),
 -0.0007499131943051906)

In [ ]:
def murals_batch(units_count, x, y, lr, epochs, bias=False, _seed=42):
    batch_size, ni = x.shape[-2:]
    units_count.insert(0, ni)
    units_count_arr = np.array(units_count)
    L, = units_count_arr.shape  # Number of layers + 1
    # RED ALERT - `as_strided` function is like a LAND-MINE ready to explode in wrong hands!
    arr_view = as_strided(units_count_arr, shape=(L-1, 2), strides=(4, 4))
#     print(arr_view)
    rng = np.random.default_rng(seed=_seed)
    wghts = [None]*(L-1)
    intercepts = [None]*(L-1)
    # WEIGHTS INITIALIZATION
    for i in range(L-1):
        w_cols, w_rows = arr_view[i, :]
        wghts[i] = rng.random((w_rows, w_cols))
        if bias:
            intercepts[i] = rng.random((w_rows,))
    costs = np.zeros(epochs)
    # Gradient Descent
    for epoch in range(epochs):
        # FORWARD PROPAGATION
        # hidden layer 1 implementation, relu activation
        h1a = np.einsum('hi,Bi -> Bh', wghts[0], x)
        if bias:
            h1a = h1a + intercepts[0]
        h1 = relu(h1a)
        # hidden layer 2 implementation, softmax activation
        h2a = np.einsum('ho,Bo -> Bh', wghts[1], h1)
        if bias:
            h2a = h2a + intercepts[1]
        hyp = softmax(h2a, _axis=1)
        current_epoch_cost = -np.einsum('Bi,Bi', y, np.log(hyp))/batch_size
#         print(current_epoch_cost)
        costs[epoch] = current_epoch_cost
        # BACKWARD PROPAGATION
        # layer 2
        dJ_dH2a = hyp - y
        dJ_dW1 = np.einsum('Bi,Bj -> ij', dJ_dH2a, h1)/batch_size
        # layer 1
        dJ_dH1 = np.einsum('Bi,ij -> Bj', dJ_dH2a, wghts[1])
        dJ_dH1a = dJ_dH1*relu_prime(h1a)
        dJ_dW0 = np.einsum('Bi,Bj -> ij', dJ_dH1a, x)/batch_size
        if bias:
            dJ_dB1 = np.einsum("Bi -> i", dJ_dH2a)/batch_size
            dJ_dB0 = np.einsum("Bi -> i", dJ_dH1a)/batch_size
        # WEIGHTS ADJUSTMENT
        wghts[1] = wghts[1] - lr*dJ_dW1
        wghts[0] = wghts[0] - lr*dJ_dW0
        if bias:
            intercepts[1] = intercepts[1] - lr*dJ_dB1
            intercepts[0] = intercepts[0] - lr*dJ_dB0
    if bias:
        return (costs, wghts, intercepts)
    else:
        return (costs, wghts)


iris = load_iris()
x = iris.data
y = iris.target
# NORMALIZE
x_norm = normalize(x)
x_train, x_test, y_train, y_test = train_test_split(
    x_norm, y, test_size=0.33, shuffle=True, random_state=42)
# BINARIZE
y_train = binarize(y_train)
y_test = binarize(y_test)
unit_per_layer_counts = [10, 3]
costs, fw, fb = murals_batch(
    unit_per_layer_counts, x_train, y_train, lr=0.01, epochs=19000, bias=True)
plt.plot(costs)


def predict(x, fw, fb):
    h1a = np.einsum(’hi, Bi -> Bh’, fw[0], x)+fb[0]
    h1 = relu(h1a)
    h2a = np.einsum(’ho, Bo -> Bh’, fw[1], h1)+fb[1]
    return softmax(h2a)
